version: "3.8"

services:
  db:
    image: mysql/mysql-server:latest
    container_name: db
    command: [
      '--bind-address=0.0.0.0'
    ]
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: 'ProjectPracticeDB'
      MYSQL_ROOT_HOST: '172.18.0.1'
    ports:
      - '8086:3306'
    expose:
      - '8086'
    volumes:
      - ./mysql:/var/lib/mysql:rw,delegated
    restart: always  

  backend:
    image: ghcr.io/projectpracticeservice/server/image:latest
    container_name: backend
    depends_on:
      - db
    ports:
      - '8080:8080'
    expose:
      - '8080'
    restart: always

