version: "3.8"

services:
  db:
    image: mysql/mysql-server:latest
    container_name: db
    cap_add:
      - SYS_NICE
    command: [
      '--bind-address=0.0.0.0'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: 'ProjectPracticeDB'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
    restart: always  

  backend:
    image: ghcr.io/projectpracticeservice/server/image:latest
    container_name: backend
    depends_on:
      - db
    ports:
      - '8080:8080'
    expose:
      - '8080'
    restart: always

volumes:
  db:
    driver: local
 
