version: "3.8"

services:
  db:
    image: mysql/mysql-server:latest
    container_name: db
    cap_add:
      - SYS_NICE
    command:
      --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: 'YjrbfAjhtdth'
      MYSQL_DATABASE: 'ProjectPracticeDB'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local 
  
