version: "3.8"

services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - 3306:3306
    restart: always

  backend:
    image: ghcr.io/projectpracticeservice/server/image:latest
    container_name: backend
    environment:
      MYSQL_USERNAME: $MYSQL_USERNAME
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_PORT: $MYSQL_PORT
      JWT_SECRET_ACCESS: $JWT_SECRET_ACCESS
      JWT_SECRET_REFRESH: $JWT_SECRET_REFRESH
    depends_on:
      - db
    links:
      - db:mysql
    ports:
      - 0.0.0.0:9090:9090
    restart: always