name: Apply commands on remote

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
    - name: Apply commands on remote
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        port: ${{ secrets.SERVER_PORT }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          DOCKER_PATH=/root/Docker
          DOCKER_COMPOSE_FILE=$DOCKER_PATH/docker-compose.yml
          REPOSITORY_URL=https://github.com/${{ github.repository }}.git
          if [ -d $DOCKER_PATH ]; then 
            if [ -d ${DOCKER_PATH}/.git ]; then
              git --work-tree=$DOCKER_PATH --git-dir=${DOCKER_PATH}.git pull
            else
              git clone $REPOSITORY_URL $DOCKER_PATH
            fi
          else
            git clone $REPOSITORY_URL $DOCKER_PATH
          fi
          export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
          docker-compose -f $DOCKER_COMPOSE_FILE pull
          docker-compose -f $DOCKER_COMPOSE_FILE up --detach
